language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/topups

node_js:  
  - 12

before_script:
  - psql -c 'create database  topups;' -U postgres
  - psql -U postgres -d topups -a -f ./sql/db.sql

services:
  - postgresql